name: 'Publish application'
env:
  PUBLISH_DIR: bin/Release/netcoreapp3.1/publish/wwwroot
  
on:
  push:
    branches : [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.x

        # Generate the website
        - name: Publish
          run: dotnet publish RazorApp/RazorApp.csproj --configuration Release
          
          
        # Publish the website
        - name: GitHub Pages action
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: RazorApp/bin/Release/netcoreapp3.1/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            # TODO uncomment the following line if you have a custom domain name
            # cname: demo.meziantou.net